### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Wandalen** [rahulshc/hello-rust#1]
How is it? Do you like Rust?

**Comment by rahulshc** [comment]
@Wandalen Hi Kos, Yes absolutely, I love it! I love their approach of how to attain performance of a manual garbage collected language like C/C++ with the advantage of not doing garbage collection on our own in the run time. I can't wait to try my hand on building some useful web and system applications in Rust and benchmark the performance difference. I just got started hence it might take some time for me to reach that point.

What is your Take on Rust? I observed you are gradually shifting from nodejs to rust or maybe using both in conjunction.

**Comment by Wandalen** [comment]
Yes. That's right. 
We promote [Rust in Ukraine](https://github.com/rust-lang-ua).
